name: asia_project
description: "Efficient and secure attendance system, using Flutter for cross-platform development and Firebase as backend. The system will be facial recognition, dynamic QR code generation, user, role and device management, and BI reporting."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0  # Cambiar a esta versión
  firebase_auth: ^5.3.3  # Versión más reciente de Firebase Auth
  firebase_core_web: ^2.10.0
  firebase_database:
  cloud_firestore: ^5.5.1
  qr_flutter: ^4.1.0
  otp: ^3.1.4
  mobile_scanner: ^6.0.2
  intl: ^0.20.1
  fl_chart: ^0.69.2  # Asegúrate de tener esta dependencia para graficar
  pdf: ^3.11.1
  printing: ^5.13.4
  excel: ^2.0.7
  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/filtra-logo.png
  uses-material-design: true
