name: asia_project
description: "Efficient and secure attendance system, using Flutter for cross-platform development and Firebase as backend. The system will be facial recognition, dynamic QR code generation, user, role and device management, and BI reporting."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0  # Cambiar a esta versión
  firebase_auth: ^5.3.3  # Versión más reciente de Firebase Auth
  firebase_core_web: ^2.10.0
  firebase_database:
  cloud_firestore: ^5.5.1
  qr_flutter: ^4.1.0
  otp: ^3.1.4
  mobile_scanner: ^6.0.2
  intl: ^0.20.1
  google_mlkit_commons: ^0.9.0
  excel: ^2.0.7
  fl_chart: ^0.69.2
  pdf: ^3.10.5
  printing: ^5.10.0
  universal_html: ^2.2.4
  google_mlkit_face_detection: ^0.12.0
  tflite_flutter: ^0.11.0
  image: ^4.3.0
  camera: ^0.10.5+9
  sqflite: ^2.4.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

# To add assets to your application, add an assets section, like this:
assets:
  - images/
  - assets/
  - assets/mobile_face_net.tflite

# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# For details regarding adding assets from package dependencies, see
# https://flutter.dev/to/asset-from-package

# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package