// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJzf6fubiBHovcZVEyZaRBn7D23vxfOu4',
    appId: '1:810833966441:web:dafe7494a70efefaab39f8',
    messagingSenderId: '810833966441',
    projectId: 'asia-flutter-riwi',
    authDomain: 'asia-flutter-riwi.firebaseapp.com',
    storageBucket: 'asia-flutter-riwi.firebasestorage.app',
    measurementId: 'G-JP1BB7MV3T', databaseURL: "https://asia-flutter-riwi.firebaseio.com"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVYEXGO_cgZNUltd0uFZ-osJdwglzeuE',
    appId: '1:810833966441:android:ebf7b05de99e3268ab39f8',
    messagingSenderId: '810833966441',
    projectId: 'asia-flutter-riwi',
    storageBucket: 'asia-flutter-riwi.firebasestorage.app',
    databaseURL: "https://asia-flutter-riwi.firebaseio.com"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7LzrR9XDVfpGrRZIqXgJ6U89O9LB6Ft8',
    appId: '1:810833966441:ios:56fc40413af7859bab39f8',
    messagingSenderId: '810833966441',
    projectId: 'asia-flutter-riwi',
    storageBucket: 'asia-flutter-riwi.firebasestorage.app',
    iosBundleId: 'io.riwi.asiaProject',
      databaseURL: "https://asia-flutter-riwi-default-rtdb.firebaseio.com"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7LzrR9XDVfpGrRZIqXgJ6U89O9LB6Ft8',
    appId: '1:810833966441:ios:56fc40413af7859bab39f8',
    messagingSenderId: '810833966441',
    projectId: 'asia-flutter-riwi',
    storageBucket: 'asia-flutter-riwi.firebasestorage.app',
    iosBundleId: 'io.riwi.asiaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJzf6fubiBHovcZVEyZaRBn7D23vxfOu4',
    appId: '1:810833966441:web:4e68f89521353405ab39f8',
    messagingSenderId: '810833966441',
    projectId: 'asia-flutter-riwi',
    authDomain: 'asia-flutter-riwi.firebaseapp.com',
    storageBucket: 'asia-flutter-riwi.firebasestorage.app',
    measurementId: 'G-ZSZP0ERDBP',
  );

}